name: 'dbt_datavault_example'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]
asset-paths: ["assets"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_datavault_example:

    d__business_vault:
      reporting_tables:
        +materialized: table

    c__raw_vault:
      # Typically we configure from within the model, but you can do this here to
      # make default the datavault hubs, sats, and links to incremental.
      +materialized: incremental